version: '2'
services:
  acme-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/acme/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=acme
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
